---
- name: Iniciar entorno virtual e instalar dependencias app vote
  ansible.builtin.shell: |
    python3 -m venv venv
    source venv/bin/activate && pip install -r requirements.txt
  args:
    chdir: /home/vagrant/app/roxs-voting-app/vote
    executable: /bin/bash

- name: Crear servicio systemd para Gunicorn (como root para usar puerto 80)
  ansible.builtin.copy:
    dest: /etc/systemd/system/gunicorn-vote.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve Vote
      After=network.target

      [Service]
      User=root
      Group=www-data
      WorkingDirectory=/home/vagrant/app/roxs-voting-app/vote
      Environment="PATH=/home/vagrant/app/roxs-voting-app/vote/venv/bin"
      ExecStart=/home/vagrant/app/roxs-voting-app/vote/venv/bin/gunicorn -w 4 -b 0.0.0.0:80 app:app

      [Install]
      WantedBy=multi-user.target

- name: Recargar systemd y habilitar Gunicorn
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl enable gunicorn-vote
    systemctl restart gunicorn-vote
    systemctl status gunicorn-vote
  become: true
