---
- name: Instalar PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Asegurarse de que el servicio PostgreSQL esté activo
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Crear base de datos votes
  become: true
  become_user: postgres
  postgresql_db:
    name: votes
    state: present

- name: Crear usuario postgres (si no existe) y establecer contraseña
  become: true
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "postgres"
    role_attr_flags: "LOGIN"

- name: Otorgar todos los privilegios en la base de datos votes al usuario postgres
  become: true
  become_user: postgres
  postgresql_privs:
    db: votes
    roles: postgres
    type: database
    privs: ALL
    state: present


