services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - wordpress-net

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp-vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wordpress-net

volumes:
  db-vol:
  wp-vol:

networks:
  wordpress-net:

