---
- name: Actualizar caché APT
  apt:
    update_cache: yes

- name: Instalar paquetes comunes
  apt:
    name:
      - curl
      - python3-pip
      - python3-venv
      - python3-psycopg2
    state: present

- name: Instalar Node.js y npm
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs
  args:
    executable: /bin/bash

- name: Instalar PM2 global
  npm:
    name: pm2
    global: yes

- name: Clonar el repositorio de la app
  ansible.builtin.git:
    repo: https://github.com/roxsross/roxs-devops-project90.git
    dest: /home/vagrant/app
    version: master
    force: yes
  become_user: vagrant

