---
- name: Reemplazar el puerto en worker main.js
  ansible.builtin.replace:
    path: /home/vagrant/app/roxs-voting-app/worker/main.js
    regexp: 'const port = 3000;'
    replace: 'const port = 3001;'

- name: Escuchar en 0.0.0.0 en worker main.js
  ansible.builtin.replace:
    path: /home/vagrant/app/roxs-voting-app/worker/main.js
    regexp: 'app.listen\(port, \(\)'
    replace: 'app.listen(port, "0.0.0.0", ()'

- name: Ajustar host de base de datos en worker main.js
  ansible.builtin.replace:
    path: /home/vagrant/app/roxs-voting-app/worker/main.js
    regexp: 'host: process.env.DATABASE_HOST \|\| "database"'
    replace: 'host: process.env.DATABASE_HOST || "localhost"'

- name: Ajustar host de Redis en worker main.js
  ansible.builtin.replace:
    path: /home/vagrant/app/roxs-voting-app/worker/main.js
    regexp: 'let hostname = process.env.REDIS_HOST \|\| "redis";'
    replace: 'let hostname = process.env.REDIS_HOST || "localhost";'

- name: Instalar dependencias con npm en worker
  npm:
    path: /home/vagrant/app/roxs-voting-app/worker
  become_user: vagrant

- name: Iniciar servicio worker con PM2 (sin startup)
  shell: |
    pm2 start main.js --name vote-worker -- -p 3001
    pm2 save
  args:
    chdir: /home/vagrant/app/roxs-voting-app/worker
  become_user: vagrant

- name: Configurar PM2 para iniciar con systemd
  shell: |
    env PATH=$PATH:/usr/bin pm2 startup systemd -u vagrant --hp /home/vagrant
  become: true

