Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "RoxsVotingApp"
  config.vm.network "private_network", ip: "192.168.33.20"
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # app result
  config.vm.network "forwarded_port", guest: 3000, host: 3001 # app worker metrics

  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
  end

  # Provisionamiento con Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = "v"
  end
end
