Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "ansible"
  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
  end

  # Provisionamiento con Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "desplegar_app.yml"
      ansible.verbose = "v"
  end
end

