
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "90daysdevops"
  config.vm.network "private_network", ip: "192.168.33.100"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  
  config.vm.provision :shell, path: "config/install-apache.sh"
  config.vm.provision "file", source: "config/index.html", destination: "/tmp/index.html"
  config.vm.provision "shell", inline: <<-SHELL
    sudo mv /tmp/index.html /var/www/html/index.html
    sudo chown www-data:www-data /var/www/html/index.html
    sudo chmod 644 /var/www/html/index.html
  SHELL

end
